<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Course;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            [
                'id' => 1,
                'title' => 'National Institute of Open Schooling',
                'code' => '9992',
                'amount' => 0,
                'hod_number' => '+91 92076 66621',
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 2,
                'title' => 'Board of Open Schooling and Skill Education',
                'code' => '9992',
                'amount' => 0,
                'hod_number' => '+91 92076 66623',
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 3,
                'title' => 'Certificate Course in Medical Coding',
                'code' => '9992',
                'amount' => 15000,
                'hod_number' => null,
                'is_active' => 1,
                'needs_time' => 1,
                'is_online' => 1,
                'is_offline' => 1,
            ],
            [
                'id' => 4,
                'title' => 'Diploma in Hospital Administration',
                'code' => '9992',
                'amount' => 20000,
                'hod_number' => null,
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 5,
                'title' => 'E-School',
                'code' => '9992',
                'amount' => 4000,
                'hod_number' => '+91 92076 66717',
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 6,
                'title' => 'Eduthanzeel',
                'code' => '9992',
                'amount' => 0,
                'hod_number' => '+91 92076 66722',
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 7,
                'title' => 'TTC',
                'code' => '9992',
                'amount' => 22000,
                'hod_number' => null,
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 8,
                'title' => 'Hotel Management',
                'code' => '9992',
                'amount' => 25000,
                'hod_number' => '+91 92076 66718',
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 9,
                'title' => 'UG/PG',
                'code' => '9992',
                'amount' => 20000,
                'hod_number' => '+91 92076 66723',
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 10,
                'title' => 'Python',
                'code' => '9992',
                'amount' => 30000,
                'hod_number' => '+91 92076 66635',
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 11,
                'title' => 'AI Integrated Digital Marketing',
                'code' => '9992',
                'amount' => 25000,
                'hod_number' => '+91 92076 66635',
                'is_active' => 1,
                'needs_time' => 1,
                'is_online' => 1,
                'is_offline' => 1,
            ],
            [
                'id' => 12,
                'title' => 'Diploma in Data Science',
                'code' => '9992',
                'amount' => 35000,
                'hod_number' => '92076 66635',
                'is_active' => 1,
                'needs_time' => 1,
                'is_online' => 1,
                'is_offline' => 1,
            ],
            [
                'id' => 13,
                'title' => 'Web Development & Designing',
                'code' => '9992',
                'amount' => 30000,
                'hod_number' => null,
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 14,
                'title' => 'Vibe Coding',
                'code' => '9992',
                'amount' => 25000,
                'hod_number' => null,
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 15,
                'title' => 'Diploma in Graphic Designing',
                'code' => '9992',
                'amount' => 0,
                'hod_number' => '+91 92076 66635',
                'is_active' => 1,
                'needs_time' => 1,
                'is_online' => 0,
                'is_offline' => 1,
            ],
            [
                'id' => 16,
                'title' => 'Grameen Mukt Vidhyalayi Shiksha Sansthan',
                'code' => '9992',
                'amount' => 15000,
                'hod_number' => '+91 92076 66628',
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 17,
                'title' => 'Others',
                'code' => null,
                'amount' => 0,
                'hod_number' => null,
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 18,
                'title' => 'fastrack',
                'code' => null,
                'amount' => 0,
                'hod_number' => null,
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 19,
                'title' => 'Hindi',
                'code' => null,
                'amount' => 0,
                'hod_number' => null,
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
            [
                'id' => 20,
                'title' => 'Diploma in Machine Learning',
                'code' => '9992',
                'amount' => 30000,
                'hod_number' => '92076 66635',
                'is_active' => 1,
                'needs_time' => 1,
                'is_online' => 1,
                'is_offline' => 1,
            ],
            [
                'id' => 21,
                'title' => 'Flutter',
                'code' => '9992',
                'amount' => 30000,
                'hod_number' => null,
                'is_active' => 1,
                'needs_time' => 0,
                'is_online' => 0,
                'is_offline' => 0,
            ],
        ];

        foreach ($courses as $course) {
            Course::updateOrCreate(
                ['id' => $course['id']],
                $course
            );
        }
    }
}
