@php
    $canToggleAcademic = \App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_academic_assistant() || \App\Helpers\RoleHelper::is_admission_counsellor();
    $canToggleSupport = \App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_support_team();
    $canManageCancelFlag = \App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor();
    $courseChanged = (bool) ($convertedLead->is_course_changed ?? false);
    $currentRegistrationLink = optional($convertedLead->studentDetails)->registrationLink;
    $registrationLinkColor = optional($currentRegistrationLink)->color_code;
@endphp

<tr class="{{ $convertedLead->is_cancelled ? 'cancelled-row' : '' }}">
    <td>{{ $displayIndex }}</td>
    <td>@include('admin.converted-leads.partials.status-badge', ['convertedLead' => $convertedLead,'type' => 'academic','showToggle' => $canToggleAcademic,'toggleUrl' => $canToggleAcademic ? route('admin.converted-leads.toggle-academic-verify', $convertedLead->id) : null,'title' => 'academic','useModal' => true])</td>
    <td>@include('admin.converted-leads.partials.status-badge', ['convertedLead' => $convertedLead,'type' => 'support','showToggle' => $canToggleSupport,'toggleUrl' => $canToggleSupport ? route('admin.support-converted-leads.toggle-support-verify', $convertedLead->id) : null,'title' => 'support','useModal' => true])</td>
    <td><div class="inline-edit" data-field="register_number" data-id="{{ $convertedLead->id }}" data-current="{{ $convertedLead->register_number }}">@if($convertedLead->register_number)<span class="badge bg-success"><span class="display-value">{{ $convertedLead->register_number }}</span></span>@else<span class="display-value text-muted">Not Set</span>@endif @if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_academic_assistant())<button class="btn btn-sm btn-outline-secondary ms-1 edit-btn" title="Edit"><i class="ti ti-edit"></i></button>@endif</div></td>
    @include('admin.converted-leads.partials.inline-course-flag-cell', ['convertedLead' => $convertedLead])
    <td>{{ $convertedLead->created_at->format('d-m-Y') }}</td>
    <td><div class="d-flex align-items-center"><div class="avtar avtar-s rounded-circle bg-light-success me-2 d-flex align-items-center justify-content-center"><span class="f-16 fw-bold text-success">{{ strtoupper(substr($convertedLead->name, 0, 1)) }}</span></div><div><h6 class="mb-0">{{ $convertedLead->name }}</h6><small class="text-muted">ID: {{ $convertedLead->lead_id }}</small>@if($convertedLead->is_cancelled)<div><span class="badge bg-danger mt-1">Cancelled</span>@if($convertedLead->cancelledBy)<br><small class="text-muted mt-1 d-block">By: {{ $convertedLead->cancelledBy->name }}@if($convertedLead->cancelled_at)<br>{{ $convertedLead->cancelled_at->format('d-m-Y h:i A') }}@endif</small>@endif</div>@endif</div></div></td>
    <td>{{ $convertedLead->is_b2b == 1 ? ('B2B' . ($convertedLead->lead?->team?->name ? ' (' . $convertedLead->lead->team->name . ')' : '')) : 'In House' }}</td>
    <td><div class="inline-edit" data-field="phone" data-id="{{ $convertedLead->id }}" data-current="{{ $convertedLead->phone }}"><span class="display-value">{{ \App\Helpers\PhoneNumberHelper::display($convertedLead->code, $convertedLead->phone) }}</span>@if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_academic_assistant())<button class="btn btn-sm btn-outline-secondary ms-1 edit-btn" title="Edit"><i class="ti ti-edit"></i></button>@endif</div><div class="d-none inline-code-value" data-field="code" data-id="{{ $convertedLead->id }}" data-current="{{ $convertedLead->code }}"></div></td>
    <td>@if($convertedLead->leadDetail && $convertedLead->leadDetail->whatsapp_number){{ \App\Helpers\PhoneNumberHelper::display($convertedLead->leadDetail->whatsapp_code, $convertedLead->leadDetail->whatsapp_number) }}@else<span class="text-muted">N/A</span>@endif</td>
    @if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor())
    <td>@if($convertedLead->leadDetail && $convertedLead->leadDetail->parents_number){{ \App\Helpers\PhoneNumberHelper::display($convertedLead->leadDetail->parents_code, $convertedLead->leadDetail->parents_number) }}@else<span class="text-muted">N/A</span>@endif</td>
    @endif
    <td><div class="inline-edit" data-field="batch_id" data-id="{{ $convertedLead->id }}" data-course-id="{{ $convertedLead->course_id }}" data-current-id="{{ $convertedLead->batch_id }}"><span class="display-value">{{ $convertedLead->batch ? $convertedLead->batch->title : 'N/A' }}</span>@if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_academic_assistant())<button class="btn btn-sm btn-outline-secondary ms-1 edit-btn" title="Edit"><i class="ti ti-edit"></i></button>@endif</div></td>
    <td><div class="inline-edit" data-field="admission_batch_id" data-id="{{ $convertedLead->id }}" data-batch-id="{{ $convertedLead->batch_id }}" data-current-id="{{ $convertedLead->admission_batch_id }}"><span class="display-value">{{ $convertedLead->admissionBatch ? $convertedLead->admissionBatch->title : 'N/A' }}</span>@if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_academic_assistant())<button class="btn btn-sm btn-outline-secondary ms-1 edit-btn" title="Edit"><i class="ti ti-edit"></i></button>@endif</div></td>
    @include('admin.converted-leads.partials.inline-finance-approval-cell', ['convertedLead' => $convertedLead])
    @include('admin.converted-leads.partials.inline-faculty-cell', ['convertedLead' => $convertedLead])
    <td><div class="inline-edit" data-field="class" data-id="{{ $convertedLead->id }}" data-current="{{ $convertedLead->leadDetail?->class }}"><span class="display-value">@if($convertedLead->leadDetail?->class){{ $convertedLead->leadDetail->class === 'sslc' ? 'SSLC' : ($convertedLead->leadDetail->class === 'plustwo' ? 'Plus Two' : $convertedLead->leadDetail->class) }}@else-@endif</span>@if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_academic_assistant())<button class="btn btn-sm btn-outline-secondary ms-1 edit-btn" title="Edit"><i class="ti ti-edit"></i></button>@endif</div></td>
    <td>{{ $convertedLead->email ?? 'N/A' }}</td>
    <td>{{ $convertedLead->course ? $convertedLead->course->title : 'N/A' }}</td>
    <td>{{ $convertedLead->lead?->studentDetails?->passed_year ?? 'N/A' }}</td>
    <td><div class="inline-edit" data-field="enroll_no" data-id="{{ $convertedLead->id }}" data-current="{{ $convertedLead->enroll_no }}"><span class="display-value">{{ $convertedLead->enroll_no ?? 'N/A' }}</span>@if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_academic_assistant())<button class="btn btn-sm btn-outline-secondary ms-1 edit-btn" title="Edit"><i class="ti ti-edit"></i></button>@endif</div></td>
    <td><div class="inline-edit" data-field="registration_link_id" data-id="{{ $convertedLead->id }}" data-current="{{ $convertedLead->studentDetails?->registration_link_id }}"><span class="display-value fw-semibold">{{ $currentRegistrationLink?->title ?? 'N/A' }}</span>@if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_academic_assistant() || \App\Helpers\RoleHelper::is_finance())<button class="btn btn-sm btn-outline-secondary ms-1 edit-btn" title="Edit"><i class="ti ti-edit"></i></button>@endif</div></td>
    <td><div class="inline-edit" data-field="certificate_status" data-id="{{ $convertedLead->id }}" data-current="{{ $convertedLead->studentDetails?->certificate_status }}"><span class="display-value">{{ $convertedLead->studentDetails?->certificate_status ?? 'N/A' }}</span>@if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_academic_assistant())<button class="btn btn-sm btn-outline-secondary ms-1 edit-btn" title="Edit"><i class="ti ti-edit"></i></button>@endif</div></td>
    <td><div class="inline-edit" data-field="certificate_received_date" data-id="{{ $convertedLead->id }}" data-current="{{ $convertedLead->studentDetails?->certificate_received_date }}">@php $receivedDate = $convertedLead->studentDetails?->certificate_received_date ? (strtotime($convertedLead->studentDetails->certificate_received_date) ? date('d-m-Y', strtotime($convertedLead->studentDetails->certificate_received_date)) : $convertedLead->studentDetails->certificate_received_date) : 'N/A'; @endphp <span class="display-value">{{ $receivedDate }}</span>@if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_academic_assistant())<button class="btn btn-sm btn-outline-secondary ms-1 edit-btn" title="Edit"><i class="ti ti-edit"></i></button>@endif</div></td>
    <td><div class="inline-edit" data-field="certificate_issued_date" data-id="{{ $convertedLead->id }}" data-current="{{ $convertedLead->studentDetails?->certificate_issued_date }}">@php $issuedDate = $convertedLead->studentDetails?->certificate_issued_date ? (strtotime($convertedLead->studentDetails->certificate_issued_date) ? date('d-m-Y', strtotime($convertedLead->studentDetails->certificate_issued_date)) : $convertedLead->studentDetails->certificate_issued_date) : 'N/A'; @endphp <span class="display-value">{{ $issuedDate }}</span>@if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_academic_assistant())<button class="btn btn-sm btn-outline-secondary ms-1 edit-btn" title="Edit"><i class="ti ti-edit"></i></button>@endif</div></td>
    <td><div class="inline-edit" data-field="remarks" data-id="{{ $convertedLead->id }}" data-current="{{ $convertedLead->studentDetails?->remarks }}"><span class="display-value">{{ $convertedLead->studentDetails?->remarks ?? 'N/A' }}</span>@if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_academic_assistant())<button class="btn btn-sm btn-outline-secondary ms-1 edit-btn" title="Edit"><i class="ti ti-edit"></i></button>@endif</div></td>
    <td><div role="group"><a href="{{ route('admin.converted-leads.show', $convertedLead->id) }}" class="btn btn-sm btn-outline-primary" title="View Details"><i class="ti ti-eye"></i></a><a href="{{ route('admin.invoices.index', $convertedLead->id) }}" class="btn btn-sm btn-success" title="View Invoice"><i class="ti ti-receipt"></i></a>@if($canManageCancelFlag)@php $cancelBtnClass = $convertedLead->is_cancelled ? 'btn-danger' : 'btn-outline-danger'; $cancelBtnTitle = $convertedLead->is_cancelled ? 'Update cancellation confirmation' : 'Confirm cancellation'; @endphp <button type="button" class="btn btn-sm {{ $cancelBtnClass }} js-cancel-flag" title="{{ $cancelBtnTitle }}" data-cancel-url="{{ route('admin.converted-leads.cancel-flag', $convertedLead->id) }}" data-modal-title="Cancellation Confirmation"><i class="ti ti-ban"></i></button>@endif @if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_academic_assistant() || \App\Helpers\RoleHelper::is_admission_counsellor() || \App\Helpers\RoleHelper::is_support_team())<button type="button" class="btn btn-sm btn-info update-register-btn" title="Update Register Number" data-url="{{ route('admin.converted-leads.update-register-number-modal', $convertedLead->id) }}" data-title="Update Register Number"><i class="ti ti-edit"></i></button>@if(\App\Helpers\RoleHelper::is_admin_or_super_admin() || \App\Helpers\RoleHelper::is_admission_counsellor())<button type="button" class="btn btn-sm {{ $courseChanged ? 'btn-success' : 'btn-danger' }} js-change-course-modal" title="Change Course" data-modal-url="{{ route('admin.converted-leads.change-course-modal', $convertedLead->id) }}" data-modal-title="Change Course"><i class="ti ti-exchange"></i></button>@endif @if($convertedLead->register_number)@if($hasIdCard)<a href="{{ route('admin.converted-leads.id-card-view', $convertedLead->id) }}" class="btn btn-sm btn-success" title="View ID Card" target="_blank"><i class="ti ti-id"></i></a>@else<form action="{{ route('admin.converted-leads.id-card-generate', $convertedLead->id) }}" method="post" style="display:inline-block" class="id-card-generate-form">@csrf<button type="submit" class="btn btn-sm btn-warning" title="Generate ID Card" data-loading-text="Generating..."><i class="ti ti-id"></i></button></form>@endif @endif @endif</div></td>
</tr>

